### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by aalvarado**
Not finished yet, but we can start tracking progress.

### CODE REVIEW

**Comment by EnriqueVidal** [comment]
It looks a lot nicer, but breaks the signing page, also it'd be cool if we could somehow load the theme css on the page down preview.

**Comment by aalvarado** [comment]
@EnriqueVidal sign in page was fixed.

**Comment by aalvarado** [comment]
@EnriqueVidal checked old pr's, wondering if you want to check this out and merge/close?

**Comment by EnriqueVidal** [comment]
Haven't checked this project in a while would need to run it first see if it's working. I'll probably do it this weekend.

**Comment by aalvarado** [comment]
:+1:

**Comment by aalvarado** [comment]
just cleaning old pr's out. reopen if needed.

**Pull request closed without merging**
