### PR TITLE
Basic improvements

### PR DESCRIPTION
**Pull request by EnriqueVidal**
Improvements include:
1. Using `friendly_id`
2. Really use the asset pipeline
3. Basic code refactor to remove deprecation warnings
4. Include `quiet_assets`
5. Update specs accordingly
6. Use `will_paginate` instead of  `kaminari`
7. Use newer version of `rails`

/cc @alexperto, @aalvarado, @alejandrom

### CODE REVIEW

**Comment by EnriqueVidal** [comment]
These are some improvements on the existing code, @aalvarado how do you feel about the following:
1. Getting rid of `wymeditor` and storing html altogether
2. Removing `jquery-ui`
3. Add `bootstrap-sass`
4. Switch to markdown
5. Add user invitations
6. Bring back **RBAC**
7. Replace `paperclip` with `carrierwave`

**Comment by aalvarado** [comment]
here!
and checking it out

**Comment by aalvarado** [comment]
@EnriqueVidal Will the cms be for ourselves only, or is this something we are going to offer to clients as well?

**Comment by EnriqueVidal** [comment]
I think both, the idea behind invitations is to delegate tasks to other users.

**Comment by aalvarado** [comment]
got it. Everything seems like we need it. I like where this is going. :+1:

**Comment by aalvarado** [comment]
I dont have further comments, you can probably merge this.

**Pull request merged**
